CXX		= CC
CC		= gcc
#CC		= cc -Aa -D_HPUX_SOURCE

MOTIF_INC	= /usr/include/Motif1.2
X11_INC		= /usr/include/X11R5

MOTIF_LIB	= /usr/lib/Motif1.2
X11_LIB		= /usr/lib/X11R5

CFLAGS         	+= -g
#CFLAGS		+= -O3
CFLAGS		+= -DSTRIPTOOLDLG_MAIN -DSTRIPCONFIG_MAIN
CFLAGS 		+= -I$(MOTIF_INC) -I$(X11_INC)

USR_LDFLAGS = -L$(MOTIF_LIB) -L$(X11_LIB) 
USR_LDLIBS = -lXm -lXt -lX11 -lm

sdtest: StripCurve.o StripToolDialog.o ColorDialog.o
	$(CC) $(CFLAGS) StripToolDialog.o StripCurve.o ColorDialog.o \
	$(USR_LDFLAGS) $(USR_LDLIBS) \
	-o sdtest

sdtest_tc: StripCurve.o StripToolDialog.o ColorDialog.o
	proof $(CC) $(CFLAGS) StripToolDialog.o StripCurve.o ColorDialog.o \
	$(USR_LDFLAGS) $(USR_LDLIBS) \
	-o sdtest_tc

sctest: StripConfig.h StripConfig.c
	$(CC) $(CFLAGS) StripConfig.c \
	$(USR_LDFLAGS) $(USR_LDLIBS) \
	-o sctest


clean:
	rm -rf 	StripCurve.o StripToolDialog.o ColorDialog.o sdtest* sctest